### ISSUE TITLE
Include readme?

### ISSUE THREAD

**Issue by Marfusios** [NeuroXiq/RobiniaDocs#2]
Hey, the project looks great! 

Would it be possible to include also `readme.md` from the library Github repo? 
Usually, the readme contains valuable info and usage examples.

**Comment by NeuroXiq** [comment]
Hello!
I totally agree that including readme (and other docs from github) is a good idea. Currently I'am working on this feature but right not it is not ready yes but it will be soon possible to include readme.md on robiniadocs :)

**Comment by NeuroXiq** [comment]
@Marfusios 
I upgraded project, now it includes README.md as project main page :)
Main page:
https://dndocs.com/d/websocket-client/index.html
Websocket-client API browser:
https://dndocs.com/d/websocket-client/api/Websocket.Client.html

I think this task is done, I migrating this repository to 'DNDocs' so I closing this issue.

Please also note that I changed a little domain name, from robiniadocs into dndocs, so URL's are now shorter a little :)
Because of name change, repo was moved to: https://github.com/NeuroXiq/DNDocs
If You have any other ideas for features/improvements or questions feel free to open discussion on [DNDocs](https://github.com/NeuroXiq/DNDocs) repo.

Regards 
NeuroXiq
